name: Check for broken links

on:
  push:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "!.github/workflows/axe.yml"
      - "!.github/workflows/deploy-docker-tag.yml"
      - "!.github/workflows/deploy-image.yml"
      - "!.github/workflows/docker-slim.yml"
      - "!.github/workflows/lighthouse-badger.yml"
      - "!.github/workflows/prettier.yml"
      - "!lighthouse_results/**"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "!.github/workflows/axe.yml"
      - "!.github/workflows/deploy-docker-tag.yml"
      - "!.github/workflows/deploy-image.yml"
      - "!.github/workflows/docker-slim.yml"
      - "!.github/workflows/lighthouse-badger.yml"
      - "!.github/workflows/prettier.yml"
      - "!lighthouse_results/**"

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up CA Certificate
        run: |
          echo "${{ secrets.CA_CERT }}" > certs/stanford_ssl_chain.pem

      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v2.1.0
        with:
          fail: true
          args: >
            --exclude-path README.md
            --exclude-path _pages/404.md
            --exclude-path _pages/blog.md
            --exclude-path _posts/2018-12-22-distill.md
            --exclude '^(https|http)://www\.linkedin\.com'
            --verbose
            --no-progress
            './**/*.md'
            './**/*.html'
        env:
          SSL_CERT_FILE: certs/stanford_ssl_chain.pem
