name: Check for broken links

on:
  push:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "!.github/workflows/axe.yml"
      - "!.github/workflows/deploy-docker-tag.yml"
      - "!.github/workflows/deploy-image.yml"
      - "!.github/workflows/docker-slim.yml"
      - "!.github/workflows/lighthouse-badger.yml"
      - "!.github/workflows/prettier.yml"
      - "!lighthouse_results/**"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "!.github/workflows/axe.yml"
      - "!.github/workflows/deploy-docker-tag.yml"
      - "!.github/workflows/deploy-image.yml"
      - "!.github/workflows/docker-slim.yml"
      - "!.github/workflows/lighthouse-badger.yml"
      - "!.github/workflows/prettier.yml"
      - "!lighthouse_results/**"

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up CA Certificate
        run: |
          mkdir -p certs
          echo "${{ secrets.CA_CERT }}" > certs/ca_certificate.pem

      - name: Download Lychee
        run: |
          if [[ "${LYCHEE_VERSION}" =~ ^v0\.0|^v0\.1[0-5]\. ]]; then
            FILENAME="lychee-${LYCHEE_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
            DOWNLOAD_URL="https://github.com/lycheeverse/lychee/releases/download/${LYCHEE_VERSION}/${FILENAME}"
          else
            FILENAME="lychee-x86_64-unknown-linux-gnu.tar.gz"
            if [[ "${LYCHEE_VERSION}" == 'nightly' ]]; then
              DOWNLOAD_URL="https://github.com/lycheeverse/lychee/releases/download/nightly/${FILENAME}"
            elif [[ "${LYCHEE_VERSION}" == 'latest' ]]; then
              DOWNLOAD_URL="https://github.com/lycheeverse/lychee/releases/latest/download/${FILENAME}"
            else
              DOWNLOAD_URL="https://github.com/lycheeverse/lychee/releases/download/lychee-${LYCHEE_VERSION}/${FILENAME}"
            fi
          fi
          
          echo "Downloading from: ${DOWNLOAD_URL}"
          curl --cacert certs/ca_certificate.pem -sfLO "${DOWNLOAD_URL}"
          
          echo "Extracting ${FILENAME}"
          tar -xvzf "${FILENAME}"
          
          # Output filename for use in later steps
          echo "filename=${FILENAME}" >> $GITHUB_ENV
        shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
        env:
          SSL_CERT_FILE: certs/ca_certificate.pem
          LYCHEE_VERSION: v0.17.0

      - name: Run Link Checker 🔗
        uses: lycheeverse/lychee-action@v2.1.0
        with:
          fail: true
          args: >
            --user-agent 'curl/7.54'
            --exclude-path README.md
            --exclude-path _pages/404.md
            --exclude-path _pages/blog.md
            --exclude-path _posts/2018-12-22-distill.md
            --exclude-path _posts/2023-04-24-videos.md
            --verbose
            --no-progress
            './**/*.md'
            './**/*.html'
        env:
          SSL_CERT_FILE: certs/ca_certificate.pem
